services:
  echo:
    container_name: echo
    image: echo
    build: .
    ports:
      - "8502:8501"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      DB_URI: ${DB_URI}
